### ISSUE TITLE
Offer Realm persistence manager as a Pod

### ISSUE THREAD

**Issue by neonichu** [contentful/contentful.objc#50]
Currently, it lives in this repo as example code, we should move it to <https://github.com/contentful/contentful-persistence.objc> and offer it as a subspec.

- [x] Move into ContentfulPersistence
- [x] Make updates for latest version of Realm if needed
- [x] Update test suite if needed

**Comment by colinbrash** [comment]
It looks like `-[RealmManager relationshipsForClass:]` is very fragile/limited and not actually doing what it really needs to do.  Two things jump out at me:
1. It assumes all Realm objects are strict descendants of `RLMObject`.  This is not necessarily true since Realm allows (limited) model inheritance: https://realm.io/docs/objc/latest/#model-inheritance
2. There is no support at all for to-many relationships.

@neonichu am I missing how you intended this to work, or is this part of the experimental/unfinished aspect of the Realm persistence?

**Comment by neonichu** [comment]
@colinbrash these are indeed issues which were never addressed. I have reopened #22 to track them.

**Comment by neonichu** [comment]
This is in-progress now in this branch: <https://github.com/contentful/contentful-persistence.objc/tree/realm-support>

**Comment by neonichu** [comment]
Tests are updated locally, but Realm to-many relationships don't work with Xcode 6.4 which is still a supported version of this. So there'll be some fiddling before the updated test suite can land in `master`.

**Comment by neonichu** [comment]
Since `d9e7c3f077d55d48420b9e7f2d0e8aa87f1ae517`, the tests for this are in `master`.
