### ISSUE TITLE
CDASyncedSpace lastSyncTimestamp is not set to the timestamp of the last synchronization operation

### ISSUE THREAD

**Issue by va7map** [contentful/contentful.objc#82]
The `lastSyncTimestamp` property in CDASyncedSpace appears to represent the newest `sys.updatedAt` date among all items, rather than the "timestamp of the last synchronization operation" as indicated in the [docs](http://cocoadocs.org/docsets/ContentfulDeliveryAPI/1.0.0/Classes/CDASyncedSpace.html#//api/name/lastSyncTimestamp).

As far as I can tell, the property gets updated in these two places:

* [`-[CDASyncedSpace updateLastSyncTimestamp]`](https://github.com/contentful/contentful.objc/blob/master/ContentfulDeliveryAPI/CDASyncedSpace.m#L314-L326)
* [`-[CDASyncedSpace handleSynchronizationResponseWithArray:success:failure:]`](https://github.com/contentful/contentful.objc/blob/a42deae67e636ecd74007eeead20198c4f374011/ContentfulDeliveryAPI/CDASyncedSpace.m#L166)

The problem with this is the date of the most recently updated item is not very useful for synchronization. I think the `lastSyncTimestamp` property was really meant to help decide if enough time has passed and another sync is needed.

**Comment by loudmouth** [comment]
Hi @va7map , it looks like you are correct, and that the `lastSynceTimestamp` property on `CDASyncedSpace` is misleading. As far as moving forward with a fix, there are two considerations to take into account:

1. The `/sync` endpoint does not actually send a timestamp in the response, which means that if we want to save a timestamp...
2. The timestamp should likely be marked locally by the SDK using `NSDate`. However, as `NSDate` uses the system clock, if the end-user has changed the date/time on his or her device, this time will be inconsistent from the real world time.

I'm curious to hear your thoughts about a preferred solution, as my sense is that you are optimizing to reduce network requests.

**Comment by va7map** [comment]
I was looking for other solutions to get the timestamp when I found the `Date` HTTP response header from the `/sync` endpoint. It seems to indicate when the response is generated and is present in both initial and subsequent synchronizations.

Can that be used to set the `lastSyncTimestamp` property?

**Comment by loudmouth** [comment]
This is a great solution, we just need to beware of timezones as the header is always returned in GMT. I think it would probably be best to leave the logic of timezone adjustment up to the SDK consumer.

I will begin working on a pull request for this issue later in the week—if this delay is too long for you, just let me know if you would like to work on an implementation on your own.

**Comment by va7map** [comment]
Sounds good. I think `NSDate` handles timezone logic and conversion pretty well, so it shouldn't be an issue as long as it's parsed with the GMT timezone intact.

And no rush! I have a temporary workaround in place until the SDK is fixed.

While we're at it, would it make sense to add the `lastSyncTimestamp` property to the `NSCoding` methods so it can be retrieved from a serialized synchronized Space file?

**Comment by loudmouth** [comment]
Hey @va7map , I will have to do this first thing next week. Got bogged down with work this week.

**Comment by va7map** [comment]
Thanks for the update. Let me know if you need more details from me.

**Comment by loudmouth** [comment]
Hey @va7map , just a heads up that I started working on this today. It turns out that the `lastSyncTimestamp` was used internally by the SDK for auxiliary reasons despite it's outward facing documentation. I expect this to take another day or two.

**Comment by loudmouth** [comment]
After some serious investigation and experimentation, I am unsure if changing the date that is stored in the `lastSyncTimestamp` is something that can be done at the moment. It turns out that the intention of this property is not necessarily to signal how much time has passed since the last sync operation was performed. Rather, it is intended to be used to implement logic about updates to `Entry` and `Asset` instances. If the timestamp does _not_ reflect the most recently updated entry that was delivered during the last sync, records that were unpublished then published again will be represented in CoreData as a delete and then a create. This is in contrast to the current implementation, in which an unpublish/publish is reflected as an _update_ in CoreData. I've copied some relevant text from the reference documentation below:


Regardless of the intended functionality, there are many complex test cases and scenarios which have network stubs that will take a lot of work to recreate. Currently, the test network stubs are just pure JSON and therefore do not contain the HTTP response headers. Since an initial sync always returns all records currently available in a Space, recreating intermediate sync stubs will take quite some time, and therefore changing the behavior of `lastSyncTimestamp` will break the testing suite and  cause more work than is worth the reward. For now, it will have to remain the responsibility of the SDK consumer to keep track of the date of the last successful sync operation.

#### Reference docs
```
/**
 *  Timestamp of the last synchronization operation. 
 *
 *  Store this alongside the `syncToken` and restore it on a newly created synchronized Space to
 *  ensure that the `delegate` will be correctly informed about updates. If you fail to restore it,
 *  only create and delete operations will be reported to the delegate of a shallow synchronized Space.
 *
 */
@property (nonatomic) NSDate* __nullable lastSyncTimestamp;
```

**Comment by va7map** [comment]
Thanks for looking into this. If `lastSyncTimestamp` is used internally for another purpose, I agree that we shouldn't change that. However, perhaps it would make sense to update the documentation to clarify its role. I think that describing it as the "timestamp of the last synchronization operation" is a bit misleading because it really is the timestamp of the most recently updated entry or asset.

On the other hand, do you think it should be added to the [`NSCoding` methods](https://github.com/contentful/contentful.objc/blob/master/ContentfulDeliveryAPI/CDASyncedSpace.m#L333-L352) so it can be retrieved from a serialized synchronized Space file? Right now when I call `+[CDASyncedSpace readFromFile:client:]`, the `lastSyncTimestamp` property will remain null.

**Comment by loudmouth** [comment]
It definitely makes sense to update the documentation for this property, and I will make sure to do that this week.

and yes, I do think it should be added to the `NSCoding` methods. I will fix this in the same PR as the documentation fix.

**Comment by loudmouth** [comment]
@va7map feel free to leave comments on #86.

**Comment by va7map** [comment]
@loudmouth I appreciate your help on this
